In [37]:
import numpy as np

np.random.seed(1)

In [105]:
w1 = np.random.rand(inp_neuron, hidden_neuron)
w2 = np.random.rand(hidden_neuron, out_neuron)

def sigmoid(x):
    return 1/(1+np.exp(-x))
        
def analytic_grad(x, y):
        
    global w1, w2
    
    hid = sigmoid(np.matmul(x, w1))
    out = np.matmul(hid, w2)
        
    loss = ((y - out)**2)/2
    out_delta = (out - y)
                            
    hid_error = np.matmul(out_delta, w2.T)
    hid_delta = hid_error*hid*(1-hid)
                          
    grad_w2 = np.matmul(hid.T, out_delta)  
    grad_w1 = np.matmul(x.T, hid_delta) 
        
    return grad_w1

In [106]:
def loss(x, y, w1, w2):
                            
    lay1 = sigmoid(np.matmul(x, w1))
    lay2 = np.matmul(lay1, w2)
    loss = ((y - lay2)**2)/2
    return loss    
    
    
def numeric_grad(x, y):
        
    h = 0.0001
    global w1, w2
    
    w1[0,0] += h
    loss_h = loss(x, y, w1, w2)   # f(a+h)
        
    w1[0,0] -= h
    loss_ = loss(x, y, w1, w2)    # f(a)
        
    grad = (loss_h - loss_)/h     # (f(a+h)-f(a)) / h
    return grad

In [107]:
inp_neuron = 3
out_neuron = 1
hidden_neuron = 4

x = np.array([[1,2,3]])
y = np.array([6])

print("Analytic gradient for weight w1[0][0]", analytic_grad(x, y)[0][0])
print("Numeric gradient for weight w1[0][0]:", numeric_grad(x, y)[0][0])

Analytic gradient for weight w1[0][0] -0.12937851674416578
Numeric gradient for weight w1[0][0]: -0.12937278681235398


In [67]:
inp_neuron = 3
out_neuron = 1
hidden_neuron = 4

x = np.array([[1,2,3]])
y = np.array([6])

def sigmoid(x):
    return 1/(1+np.exp(-x))

# defining weight matrices
w1 = np.random.rand(inp_neuron, hidden_neuron)
w2 = np.random.rand(hidden_neuron, out_neuron)

# calculating activations
hid = sigmoid(np.matmul(x, w1))    
out = np.matmul(hid, w2)           
        
# defining loss function    
loss = ((y - out)**2)/2

# calculating the gredients of loss w.r.t weights
out_delta = (out - y)                         
hid_error = np.matmul(out_delta, w2.T)
hid_delta = hid_error*hid*(1-hid)                         
grad_w2 = np.matmul(hid.T, out_delta)  
grad_w1 = np.matmul(x.T, hid_delta) 

print("gradients of w1:\n\n", grad_w1)

gradients of w1:

 [[-0.28427288 -0.0467112  -0.61256146 -0.05071152]
 [-0.56854577 -0.09342239 -1.22512292 -0.10142303]
 [-0.85281865 -0.14013359 -1.83768438 -0.15213455]]
